version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=fullstack_app
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm run init-db && npm run dev"

  db:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fullstack_app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
